# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_versions=1.21.10
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.135.0+1.21.10


# Conditional Mixins plugin
conditional_mixin_version=0.6.4

# Config API
fzzyConfigVersion=0.7.2+1.21.9

# Mod Properties
mod_version = 1.12.0
mod_id = solute
mod_release_type = release
maven_group = nl.gjorgdy
archives_base_name = Solute